version: 0.0.0.{build}-{branch}
image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019
  - Ubuntu1604
  - Ubuntu1804
  - Ubuntu2004
  - macos
  - macos-mojave
install:
build_script:
  - cmd: run.cmd help
  - sh: ./run.sh help
test: off
